version: 2.1
jobs:
  build:
    parameters:
      clojure-tag:
        type: string
    machine:
      image: ubuntu-2204:2022.04.2
    working_directory: /home/circleci/migratus
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-jars-{{ checksum "project.clj" }}
            - v1-dependency-jars
      - run:
          name: run tests
          command: |
            whoami
            echo $PWD
            docker run --rm -u root -v $PWD:/home/circleci/migratus -v /var/run/docker.sock:/var/run/docker.sock -v /home/circleci/.m2:/home/circleci/.m2 -v /home/circleci/.lein:/home/circleci/.lein -w=/home/circleci/migratus cimg/clojure:<< parameters.clojure-tag >> bin/kaocha
            ls -lah
            sudo chown -R circleci:circleci /home/circleci/migratus
            ls -lah

      - store_test_results:
          path: /home/circleci/migratus/target/test-reports/
      - save_cache:
          key: v1-dependency-jars-{{ checksum "project.clj" }}
          paths:
            - /home/circleci/.m2
            - /home/circleci/.lein

workflows:
  build:
    jobs:
      - build:
          matrix:
            parameters:
              clojure-tag: ["1.10-openjdk-8.0", "1.11-openjdk-8.0", "1.11-openjdk-11.0", "1.11-openjdk-17.0"]
